import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PlayGround from "@/components/playground/PlayGround";
import { HeroHighlightComponent } from "@/components/hero-highlight/HeroHighlightComponent";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="hydrated">
      <body className={`dark text-blue-500 ${inter.className}`}>
        <HeroHighlightComponent classname="h-screen fixed top-0 "></HeroHighlightComponent>
        <div className="flex overflow-y-auto">
          <div className="w-[38vw] h-screen z-10">
            <PlayGround className="fixed top-0 left-0 w-[38vw] h-screen bg-zinc-950/60 border-r-[1.2vw] border-zinc-950" />
          </div>
          <div className="w-[62vw] h-screen pl-4 z-10">{children}</div>
        </div>
      </body>
    </html>
  );
}
